version: "3.8"

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: revobank
      MYSQL_USER: revouser
      MYSQL_PASSWORD: SecurePass123!
    ports:
      - "3000:3000"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  revobank-api:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      mysql-container:
        condition: service_healthy
    environment:
      DB_HOST: mysql-container
      DB_NAME: revobank
      DB_USER: revouser
      DB_PASSWORD: SecurePass123!
      JWT_SECRET_KEY: super_secret_key_123
    entrypoint:
      [
        "/usr/local/bin/wait-for-it.sh",
        "mysql-container:3306",
        "--",
        "flask db upgrade && gunicorn --bind 0.0.0.0:8000 app:app",
      ]

volumes:
  mysql-data:
