services:
  revobank-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONPATH: /app
    volumes:
      - ./revobank-api/app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
