"""Add cascade delete to transactions

Revision ID: f889460d7964
Revises: 8a74a9ee3fbb
Create Date: 2025-03-10 13:19:45.135543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f889460d7964'
down_revision = '8a74a9ee3fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('transactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['to_account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'accounts', ['from_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_ibfk_1', 'accounts', ['from_account_id'], ['id'])
        batch_op.create_foreign_key('transactions_ibfk_2', 'accounts', ['to_account_id'], ['id'])

    # ### end Alembic commands ###
